SELECT * FROM EMPLOYEES ;

-- CASE WHEN STATEMENT TO CONDITIONALLY DISPLAY VALUES

-- Display Employees FIRST_NAME, SALARY , SALARY_GRADE
 --- SALARY_GRADE Column should be below VALUES
    -- WHEN SALARY > 8000  "ABOVE AVERAGE"
    -- ELSE  "BELOW AVERAGE"

    SELECT FIRST_NAME, SALARY ,
                CASE
                    WHEN SALARY > 8000 THEN 'ABOVE AVERAGE'
                    ELSE  'BELOW AVERAGE'
                END AS SALARY_GRADE
    FROM EMPLOYEES ;

-- Display Employees FIRST_NAME, SALARY , SALARY_GRADE2
--- SALARY_GRADE Column should be below VALUES
-- WHEN SALARY > 20000  THEN 'A'
-- WHEN SALARY BETWEEN 10000 AND 20000  THEN 'B'
-- WHEN SALARY BETWEEN 5000 AND 10000  THEN 'C'
-- ELSE 'D'

    SELECT FIRST_NAME, SALARY , CASE
                                    WHEN SALARY > 20000  THEN 'A'
                                    WHEN SALARY BETWEEN 10000 AND 20000  THEN 'B'
                                    WHEN SALARY BETWEEN 5000 AND 10000  THEN 'C'
                                    ELSE 'D'
                                END AS SALARY_GRADE2
    FROM EMPLOYEES
    ORDER BY SALARY
    ;

--- DATE FUNCTION
-- FIND OUT EVERY EMPLOYEES HIRED BEFORE DATE 2002-08-16

-- TO_DATE ACCEPT 2 PARAMETERS
--  THE DATE STRING
--  THE FORMAT OF DATE PROVIDED IN PREVIOUS PARAMETER
SELECT FIRST_NAME , HIRE_DATE
FROM EMPLOYEES
-- WHERE HIRE_DATE < '2002-08-16' WONT WORK HERE
WHERE HIRE_DATE <  TO_DATE('2002-08-16', 'YYYY-MM-DD');
;
-- FIND OUT EVERY EMPLOYEES HIRED BETWEEN 2001-01-13 AND 2006-01-03

SELECT FIRST_NAME , HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('2001-01-13', 'YYYY-MM-DD')
                AND TO_DATE('2006-01-03', 'YYYY-MM-DD') ;


SELECT * from employees
Where job_id = 'IT_PROG'; -- for rows

SELECT *
from employees;

SELECT * FROM employees SAMPLE(2);



SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_NAME FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS;

-- Comparison operator ---BETWEEN
SELECT * FROM EMPLOYEES
where  salary between 3000 and 4000;

SELECT * FROM EMPLOYEES
where  salary not between 2000 and 4000;

SELECT * FROM EMPLOYEES
WHERE salary >= 6000 AND SALARY <=8000;

SELECT * FROM EMPLOYEES
WHERE SALARY != 8000 ;

SELECT last_name, job_id
FROM EMPLOYEES
WHERE NOT JOB_ID = 'SA-REP';

SELECT DEPARTMENT_ID
FROM EMPLOYEES
where DEPARTMENT_ID in (30,40,60);

SELECT * from employees
where JOB_ID IN ('IT_PROG','ST_MAN');

SELECT * from employees
where first_name like 'D%';

SELECT * from employees
where first_name like '%D%';

SELECT * from employees
where first_name like '%a';

SELECT * from employees
where first_name like '____%a';


SELECT DEPARTMENT_ID, min(salary)
from employees
GROUP BY DEPARTMENT_ID
HAVING  MIN(salary) <3000;

SELECT * FROM employees
WHERE DEPARTMENT_ID = 100;

SELECT * FROM employees
where EMPLOYEE_ID BETWEEN 200 AND 300
ORDER BY EMPLOYEE_ID desc;


SELECT EMPLOYEE_ID, last_name, employees.department_id, department_name
from employees JOIN DEPARTMENTS
ON employees.department_id =DEPARTMENTS.DEPARTMENT_ID;

SELECT SUBSTR (FIRST_NAME, 0,3)
FROM EMPLOYEES;

SELECT REPLACE (LAST_NAME, 'A' ,'B')
FROM EMPLOYEES;

SELECT INSTR (LAST_NAME, 'b')
FROM EMPLOYEES;

SELECT FIRST_NAME ||''|| LAST_NAME
FROM EMPLOYEES;










